CREATE TABLE example_a ();

CREATE TABLE example_b (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  --
  all_a text COLLATE "C" CONSTRAINT all_a NOT NULL DEFAULT 'default',
  all_b text COLLATE "C" CONSTRAINT all_b NOT NULL GENERATED ALWAYS AS (all_a || '!') VIRTUAL,
  all_c bigint CONSTRAINT all_c NOT NULL GENERATED ALWAYS AS IDENTITY,
  --
  simple_single integer,
  simple_array text[],
  simple_parameterized numeric(10,2),
  --
  collate_default text COLLATE "default",
  collate_local text COLLATE collation_local,
  collate_c text COLLATE "POSIX",
  --
  null_default text NULL,
  null_not text NOT NULL,
  null_not_constraint text CONSTRAINT "nn" NOT NULL,
  null_not_constraint_omit text CONSTRAINT example_b_null_not_constraint_omit_not_null NOT NULL, -- omitted
  --
  default_null integer DEFAULT NULL, -- omitted
  default_value integer DEFAULT 123,
  default_expression timestamptz DEFAULT NOW(),
  --
  generated_stored numeric(10,2) GENERATED ALWAYS AS (default_value * 1.5) STORED,
  generated_virtual text GENERATED ALWAYS AS (null_not || '!') VIRTUAL,
  --
  identity_always bigint GENERATED ALWAYS AS IDENTITY,
  identity_by_default bigint GENERATED BY DEFAULT AS IDENTITY,
  identity_sequence_simple bigint GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME identity_sequence),
  identity_sequence_default bigint GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME example_b_identity_sequence_seq
    START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
  ),
  identity_sequence_all bigint GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME identity_sequence_all
    START WITH 2 INCREMENT BY 2 MINVALUE 2 MAXVALUE 9223372036854775806 CACHE 2 CYCLE
  ),
  identity_sequence_big_numbers bigint GENERATED ALWAYS AS IDENTITY (
    START WITH 9223372036854775806
    INCREMENT BY 9223372036854775806
    MINVALUE 9223372036854775805
    MAXVALUE 9223372036854775806
    CACHE 9223372036854775806 CYCLE
  ),
  identity_sequence_no_name bigint GENERATED ALWAYS AS IDENTITY (START WITH 2 INCREMENT BY 2),
  --
  period_tstzrange tstzrange,
  --
  unique_simple integer UNIQUE,
  unique_nulls_not_distinct integer UNIQUE NULLS NOT DISTINCT,
  unique_with integer UNIQUE WITH (fillfactor = 70, deduplicate_items = off),
  unique_deferrable integer UNIQUE DEFERRABLE INITIALLY DEFERRED,
  --
  UNIQUE (unique_simple, id),
  UNIQUE (id) INCLUDE (id, id),
  CONSTRAINT u UNIQUE NULLS NOT DISTINCT (id) INCLUDE (id, id),
  --
  EXCLUDE (id WITH =) INCLUDE (id) WHERE (id > 100),
  EXCLUDE USING gist (period_tstzrange WITH &&) DEFERRABLE INITIALLY DEFERRED
);

CREATE UNLOGGED TABLE example_c (id int)
WITH (toast.autovacuum_vacuum_threshold='500');

CREATE TABLE example_d (id int, simple_text text)
WITH (fillfactor='70', parallel_workers=2, autovacuum_enabled='false', toast.autovacuum_vacuum_threshold='500');

CREATE TABLE example_e () INHERITS (example_d, example_c);

CREATE TABLE example_f1_parent (
  id integer PRIMARY KEY
);

CREATE TABLE example_f2_child (
  parent_id integer,
  FOREIGN KEY (parent_id) REFERENCES example_f1_parent
);

CREATE TABLE example_g1_parent (
  id_a integer,
  id_b integer,
  PRIMARY KEY (id_a, id_b)
);

CREATE TABLE example_g2_child (
  id_a integer,
  id_b integer,
  FOREIGN KEY (id_a, id_b) REFERENCES example_g1_parent MATCH FULL ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX ON example_g2_child (id_a);
