CREATE TABLE example_a ();

CREATE TABLE example_b (
  id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  all_a text COLLATE pg_catalog."C" CONSTRAINT all_a NOT NULL DEFAULT 'default'::text,
  all_b text COLLATE pg_catalog."C" CONSTRAINT all_b NOT NULL GENERATED ALWAYS AS (all_a || '!'::text) VIRTUAL,
  all_c bigint CONSTRAINT all_c NOT NULL GENERATED ALWAYS AS IDENTITY,
  simple_single integer,
  simple_array text[],
  simple_parameterized numeric(10,2),
  collate_default text,
  collate_local text COLLATE collation_local,
  collate_c text COLLATE pg_catalog."POSIX",
  null_default text,
  null_not text NOT NULL,
  null_not_constraint text CONSTRAINT nn NOT NULL,
  null_not_constraint_omit text NOT NULL,
  default_null integer,
  default_value integer DEFAULT 123,
  default_expression timestamp with time zone DEFAULT now(),
  generated_stored numeric(10,2) GENERATED ALWAYS AS ((default_value::numeric * 1.5)) STORED,
  generated_virtual text GENERATED ALWAYS AS (null_not || '!'::text) VIRTUAL,
  identity_always bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  identity_by_default bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  identity_sequence_simple bigint NOT NULL GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME identity_sequence),
  identity_sequence_default bigint NOT NULL GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME example_b_identity_sequence_seq),
  identity_sequence_all bigint NOT NULL GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME identity_sequence_all START WITH 2 INCREMENT BY 2 MINVALUE 2 MAXVALUE 9223372036854775806 CACHE 2 CYCLE),
  identity_sequence_big_numbers bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 9223372036854775806 INCREMENT BY 9223372036854775806 MINVALUE 9223372036854775805 MAXVALUE 9223372036854775806 CACHE 9223372036854775806 CYCLE),
  identity_sequence_no_name bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 2 INCREMENT BY 2),
  period_tstzrange tstzrange,
  unique_simple integer,
  unique_nulls_not_distinct integer,
  unique_with integer,
  unique_deferrable integer
);

ALTER TABLE ONLY example_b ADD CONSTRAINT example_b_id_id1_id2_key UNIQUE (id) INCLUDE (id, id);

ALTER TABLE ONLY example_b ADD CONSTRAINT example_b_unique_deferrable_key UNIQUE (unique_deferrable) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY example_b ADD CONSTRAINT example_b_unique_nulls_not_distinct_key UNIQUE NULLS NOT DISTINCT (unique_nulls_not_distinct);

ALTER TABLE ONLY example_b ADD CONSTRAINT example_b_unique_simple_id_key UNIQUE (unique_simple, id);

ALTER TABLE ONLY example_b ADD CONSTRAINT example_b_unique_simple_key UNIQUE (unique_simple);

ALTER TABLE ONLY example_b ADD CONSTRAINT example_b_unique_with_key UNIQUE (unique_with) WITH (fillfactor=70, deduplicate_items=off);

ALTER TABLE ONLY example_b ADD CONSTRAINT u UNIQUE NULLS NOT DISTINCT (id) INCLUDE (id, id);

ALTER TABLE ONLY example_b ADD CONSTRAINT example_b_pkey PRIMARY KEY (id);

ALTER TABLE ONLY example_b ADD CONSTRAINT example_b_id_id1_excl EXCLUDE USING btree (id WITH =) INCLUDE (id) WHERE (id > 100);

ALTER TABLE ONLY example_b ADD CONSTRAINT example_b_period_tstzrange_excl EXCLUDE USING gist (period_tstzrange WITH &&) DEFERRABLE INITIALLY DEFERRED;

CREATE UNLOGGED TABLE example_c (
  id integer
);

CREATE TABLE example_d (
  id integer,
  simple_text text
)
WITH (fillfactor=70, parallel_workers=2, autovacuum_enabled=false, toast.autovacuum_vacuum_threshold=500);

CREATE TABLE example_e ()
INHERITS (example_d, example_c);

CREATE TABLE example_f1_parent (
  id integer NOT NULL
);

ALTER TABLE ONLY example_f1_parent ADD CONSTRAINT example_f1_parent_pkey PRIMARY KEY (id);

CREATE TABLE example_f2_child (
  parent_id integer
);

ALTER TABLE ONLY example_f2_child ADD CONSTRAINT example_f2_child_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES example_f1_parent(id);

CREATE TABLE example_g1_parent (
  id_a integer NOT NULL,
  id_b integer NOT NULL
);

ALTER TABLE ONLY example_g1_parent ADD CONSTRAINT example_g1_parent_pkey PRIMARY KEY (id_a, id_b);

CREATE TABLE example_g2_child (
  id_a integer,
  id_b integer
);

ALTER TABLE ONLY example_g2_child ADD CONSTRAINT example_g2_child_id_a_id_b_fkey FOREIGN KEY (id_a, id_b) REFERENCES example_g1_parent(id_a, id_b) MATCH FULL ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX example_g2_child_id_a_idx ON example_g2_child USING btree (id_a);